#Generated by VisualKernel [http://visualkernel.com/].
#Use VisualKernel Project Properties to edit.

# Get kernel version
CURRENT = $(shell uname -r)

ifndef KERNELDIR
	KERNELDIR = /lib/modules/$(CURRENT)/build
endif
INSTALLDIR = /lib/modules/$(CURRENT)/kernel/drivers/usb

KERNEL_MODULE_NAME := DVBCIUSB
KERNEL_MODULE_OBJECT_FILE_LIST := DVBCIKernelModule.o DVBCICommandInterface.o DVBCIMediaInterface.o

obj-m := $(KERNEL_MODULE_NAME).o
$(KERNEL_MODULE_NAME)-y += $(KERNEL_MODULE_OBJECT_FILE_LIST)
ccflags-y := -ggdb -O0

all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean

INSTALL_CMD := "/sbin/rmmod $(KERNEL_MODULE_NAME) 2>/dev/null || true &&     \
				install -d $(INSTALLDIR) &&     \
	            cp -v $(KERNEL_MODULE_NAME).ko $(INSTALLDIR) && \
				install -o root -g root -m 644 10-ciusb.rules /etc/udev/rules.d && \
			    /sbin/depmod -a && \
			    /sbin/modprobe $(KERNEL_MODULE_NAME)"
install:
	su -c $(INSTALL_CMD)
